services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html:cached
    environment:
      - APP_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - symfony-react-network
      - shared-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    # command: ["npm", "start"]
    ports:
      - "3000:3000"
    networks:
      - symfony-react-network
      - shared-network

  fpm:
    build:
      context: ./backend/docker
      dockerfile: Dockerfile-php
    environment: 
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - symfony-react-network
      - shared-network

networks:
  symfony-react-network:
    driver: bridge
  shared-network:
    external: true
    name: shared-network