version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html:cached
      - ./backend/vendor:/var/www/html/vendor:delegated
    environment:
      - APP_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - symfony-react-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    # command: ["npm", "start"]
    ports:
      - "3000:3000"
    networks:
      - symfony-react-network

  fpm:
    build:
      context: ./backend/docker
      dockerfile: Dockerfile-php
    environment: 
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - symfony-react-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=zoo
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - symfony-react-network

volumes:
  mysql_data:

networks:
  symfony-react-network:
    driver: bridge