api_platform:
    title: Hello API Platform
    version: 1.0.0
    # mapping:
    #     paths: ['%kernel.project_dir%/src/Entity']
    show_webby: true
    # eager_loading:
    #     max_joins: 100
    #     force_eager: false
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        normalization_context:
            groups: ['read'] 
        denormalization_context:
            groups: ['write']
        # pagination_items_per_page: 30
        # pagination_maximum_items_per_page: 50
        # collection:
        #     pagination:
        #         enabled: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
