api_platform:
    title: Hello API Platform
    version: 1.0.0
    show_webby: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        nnormalization_context:
            groups: ['read'] 
        denormalization_context:
            groups: ['write'] 
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
